### ISSUE TITLE
Unable to get label with `create_morpho_image.sh`

### ISSUE THREAD

**Issue by cbedetti** [CoBrALab/minc-toolkit-extras#3]
Command run :

`./create_morpho_image.sh new_lefthc.obj ../lm/tvalue_CA_left_icv.csv 2.17406767435032,2.83736873702781 new_righthc.obj ../lm/tvalue_CA_right_icv.csv 2.28660590804178,2.96056946858748 tvalue-groupcatCTRL ../morpho_images/lm_CA_icv.png &> create_morpho_image.log`

I'm getting the thresholds automatically, that's why the long format. Using "normal" format does not change the issue.

The two csv files have the `tvalue-groupcatCTRL` column.

Content of create_morpho_image.log :

```
Value range: -10.3427 9.13157
Value range: -10.3427 9.13157
Value range: -8.1667 6.80638
Value range: -8.1667 6.80638
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
Ray Tracing: ..................................................................
/tmp/tmp.HtXGFYoNLc
```

Content of TMPDIR :

```
1.png
2.png
3.png
4.png
back.png
back.rgb
bottom.png
bottom.rgb
coldmetalinv.png
front.png
front.rgb
left_comb.obj
left_lateral.png
left_lateral.rgb
left_medial.png
left_medial.rgb
left_pos.obj
redmetalinv.png
right_comb.obj
right_lateral.png
right_lateral.rgb
right_medial.png
right_medial.rgb
right_pos.obj
rmincblue.map
rmincred.map
top.png
top.rgb
tvalue_CA_left_icv.csv
tvalue_CA_right_icv.csv
unlabelled.png
```

`lm_CA_icv.png`

![lm_CA_icv](https://user-images.githubusercontent.com/9487739/56064568-70024d80-5d40-11e9-8dca-0a3fb1ac8c70.png)

 `unlabelled.png`

![unlabelled](https://user-images.githubusercontent.com/9487739/56064548-624cc800-5d40-11e9-82ec-dfd50cb0ea65.png)

**Comment by gdevenyi** [comment]
Can you please upload a zip containing your data so I can do some testing.

It looks like imagmagick's version updates in the VM have changed the underlying heuristics and I'll need to play to figure out how to make it work.

**Comment by cbedetti** [comment]
[tmp.HtXGFYoNLc.tar.gz](https://github.com/CobraLab/minc-toolkit-extras/files/3080651/tmp.HtXGFYoNLc.tar.gz)

**Comment by gdevenyi** [comment]
Thanks, can I have the raw input stats files too?

**Comment by gdevenyi** [comment]
long since sorted.
