### ISSUE TITLE
Question: min and max for `ants_generate_iterations.py`

### ISSUE THREAD

**Issue by butellyn** [CoBrALab/minc-toolkit-extras#5]
Hello! I am hoping to use `ants_generate_iterations.py` to construct a more robust group template, but I am unsure what the `--min` and `--max` arguments are referring to. Are they referring to dimensions of the input images, or the dimensions of the voxels in the input images? Or something else?

**Comment by gdevenyi** [comment]
Hi @butellyn 

The `--min` and `--max` options refer to the size (in mm) of the fixed space for the registration. In the case of a ants template build, this would be resolution of the `-z` option:

```
     -z:  Use this this volume as the target of all inputs. When not used, the script
          will create an unbiased starting point by averaging all inputs. Use the full
          path.
          For multiple modalities, specify -z modality1.nii.gz -z modality2.nii.gz ...
          in the same modality order as the input images.
```

If not using `-z` it would be the minimum voxel size of all of your input files, and the largest dimension of the largest spatial extent of your largest image.


So, an example from the MNI ICBM NLIN SYM 09c template:
```
$ mincinfo $mnimodel
file: /storage/localproject/resources/mni_icbm152_nlin_sym_09c_minc2/mni_icbm152_t1_tal_nlin_sym_09c.mnc
image: unsigned short 0 to 65535
image dimensions: zspace yspace xspace
    dimension name         length         step        start
    --------------         ------         ----        -----
    zspace                    193            1          -78
    yspace                    229            1         -132
    xspace                    193            1          -96
```

The template has minimum resolution (voxel size in real space) of 1 mm (`--min 1`) and maximum extent of 229 mm (`--max 229`). This tells `ants_generate_iterations.py` the scale over which the scale space image pyramid will be constructed.

**Comment by butellyn** [comment]
Thank you!
