### ISSUE TITLE
Feature update and merge create_civet_image.sh and create_morpho_image.sh

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/minc-toolkit-extras#6]
- [ ] allow for control of colourbar labels
- [ ] allow for changing colourmaps
- [ ] allow for specifying image title
- [ ] integrate proper command line parsing
- [ ] allow for single-direction maps (no bicolour)
- [ ] provide command line for multiple morpho objects and maps
- [ ] orientations to generate
- [ ] orientation labels on/off
- [ ] background colour
- [ ] check length of inputs correspond properly to object being used.

**Comment by alyssadai** [comment]
Changing the image background, control of which orientations of the brain to show if possible, toggling orientation labels on/off.

**Comment by gdevenyi** [comment]
Imagemagick layout on Niagara with newer version is broken. No idea why.
