### ISSUE TITLE
Python environment to run t2star_fit*

### ISSUE THREAD

**Issue by jeremie-fouquet** [CoBrALab/minc-toolkit-extras#9]
Could you please share the python environment required to run the t2star_fit.py and t2star_fit_simpleitk.py functions?

I'm running into several issues when trying to install the imported packages one by one. 

Thanks.

**Comment by gdevenyi** [comment]
1) don't use t2star_fit.py
2) https://anaconda.org/SimpleITK/simpleitk, `pip install miniutils`

**Comment by gdevenyi** [comment]
pycontracts is broken with pyparsing for certain versions and a new version isn't released, manual fix,
https://github.com/pyparsing/pyparsing/issues/327
